alias qshell_refresh='docker run --rm -it -v $(pwd):/mnt jyb-qshell:13.0 qshell cdnrefresh'
alias qshell_list='docker run --rm -it -v $(pwd):/mnt jyb-qshell:13.0'
alias qshell_get='docker run --rm -it -v $(pwd):/mnt jyb-qshell:13.0 qshell_get' 
alias qshell_put='docker run --rm -it -v $(pwd):/mnt jyb-qshell:13.0 qshell_put'
alias qshell_del='docker run --rm -it -v $(pwd):/mnt jyb-qshell:13.0 qshell_del'

